### ISSUE TITLE
Problem with core-web-vitals

### ISSUE THREAD

**Issue by adri** [newrelic/nr1-quickstarts#35]
Hi! I'm getting an error importing the core-web-vitals dashboard. When checking the XHR requests, I see this error message returned from the API:

```
description: "Error parsing: SELECT percentile(firstContentfulPaint, 75), percentile(largestContentfulPaint, 75), percentile(firstInputDelay, 75), max(firstInputDelay), filter(percentile(cumulativeLayoutShift, 75), WHERE timingName = 'firstContentfulPaint') as 'Cumulative Layout Shift', percentile(pageHide, 75) FROM PageViewTiming WHERE FACET appName, browserTransactionName LIMIT 50, please check nrql grammar.↵Cause: Error at line 1 position 311, unexpected 'FACET'"
```

**Comment by kidk** [comment]
Thanks for reporting this @adri 

It seems the query has a duplicate where clause. I've fixed it and deployed the new version: https://github.com/newrelic/quickstarts-dashboard-library/commit/148c2252d4885bd2420d9fe1b8342003547bcfb4

Can you try again?

**Comment by adri** [comment]
Works awesome thanks!
